#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#include "dhtxx/dhtxx.h"

#define GPIO0_DHT_TYPE DHT22
#define GPIO2_DHT_TYPE DHT22
#define GPIO4_DHT_TYPE DHT22
#define GPIO5_DHT_TYPE DHT22
#define GPIO12_DHT_TYPE DHT22
#define GPIO13_DHT_TYPE DHT22
#define GPIO14_DHT_TYPE DHT22
#define GPIO16_DHT_TYPE DHT22

#endif
